<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/TwoColumn.Master" Inherits="T3ME.Business.ViewPages.T3meViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	Legal
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <section id="StandardContent">
        <h1>Legal Stuff</h1>

        <p>
            This website was (brilliantly) developed and (badly) designed by <a href="http://www.dominicpettifer.co.uk">Dominic Pettifer</a>.
            <%: App.Title %> is not affiliated in any way with Twitter.
        </p>

        <h2>Privacy Policy</h2>

        <p>
            This website will trawl Twitter for any "public" tweets that match specific search terms, namely certain hashtags. Thus any message you
            tweet under your Twitter account, that matches these search terms, will appear on this website, providing you have made your Twitter
            acount public. Your Twitter username and profile picture will appear alongside each tweet, along with any other "public" information
            available via the Twitter API. <%: App.Title %> won't modify any of this information.
        </p>

        <p>
            We may aggregate this information to display interesting stats, such as "Most Frequent Tweeters", or "Top Rated" tweets. We may decide to
            retweet your own tweets under our own Twitter account if it receives enough votes, though we will credit the original author. We may
            also follow your Twitter account when certain "conditions" are met (such as numbers of votes received for your tweets). The above
            precesses are fully automated, although we may decide to perform these manually from time to time.
        </p>

        <p>
            <strong>When voting, you agree to have your voting behaviour made public.</strong> When voting for your favourite <%: App.Noun.Plural.CapitaliseFirstLetter() %>,
            details of you voting will appear next to the tweet in the detail view page, thus other users can see who voted for each tweet.
            Specifically we will display your username, profile picture and a link to your Twitter page, although this is the full extent of the
            information we will publically convey about you as a user participating as a voter. 
        </p>

        <p>
            When logging in via your Twitter account, we only ask for "Read Only" access, and won't try to update your account, or post messages without
            your consent, or at all. We will request and store your Twitter acount details, specifically your Twitter ID, Username, and Profile Image URL
            (all public information), only when you vote for a tweet in order to prevent repeated voting, and for reasons detailed in the previous paragraph.
        </p>

        <h2>Terms &amp; Conditions</h2>

        <p>
            Your rights pertaining to the content trawled from Twitter, remain exactly the same as
            <a href="http://twitter.com/tos">Twitter's Terms &amp; Conditions which you can find here</a>.
        </p>

        <p>
            We reserve the right to ban or block users, either by preventing voting, or preventing their tweets from being trawled, if users
            violate the "spirit" of this website, such as by tweeting spam, marketting, or rude/abusive tweets that contain hashtags this website trawls for,
            knowing that they will appear on this website. We reserve the right to delete these tweets, and any voting data,
            from our own database if they get accidently indexed.
        </p>

        <p>
            We reserve the right to ban or block users, either by preventing voting, or preventing their tweets from being trawled, if users
            utilise multiple Twitter accounts to vote in a way that tricks this websites automated systems into retweeting a tweet, that contains spam, marketting
            or rude/abusive comments, or any other message that violates the "spirit" of this website. We reserve the right to delete these tweets, and any voting data,
            from our own database, and from our Twitter account, if they get accidently indexed.
        </p>

        <p>
            Users <em>CAN</em> vote for their own tweets if they wish. Users <em>CAN</em> vote for tweets multiple times under different Twitter accounts if they wish.
        </p>

        <h2>Google Analytics</h2>

        <p>
            This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are
            text files placed on your computer, to help the website analyze how users use the site.
        </p>

        <p>
            The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored
            by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website,
            compiling reports on website activity for website operators and providing other services relating to website activity and internet usage.
        </p>

        <p>
            Google may also transfer this information to third parties where required to do so by law, or where such third
            parties process the information on Google's behalf.
        </p>
        
        <p>
            Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by
            selecting the appropriate settings on your browser, however please note that if you do this you may not be able
            to use the full functionality of this website.
        </p>

        <p>
            By using this website, you consent to the processing of data about you by
            Google in the manner and for the purposes set out above.
        </p>

    </section>

</asp:Content>
